
#DRUGBANK_FILE_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/drtar_smallSample.bsv"
#DRUGBANK_FILE_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/drtar.bsv"
DRUGBANK_FILE_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/drtar_all.bsv"
ATC_CODE_FILE_PATH_OLD = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/dbank.dsv"
ATC_CODE_FILE_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/dbank_v2.dsv"
ATC_CODE_ADDITION_FILE_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/dbank_additional.dsv"
GO_TERM_FILE_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/uni2go.json"
DRUG_FILE_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/drugs.json"
TARGET_CLASSES_PATH = "C:/Users/tobia/Documents/FH_Hagenberg_MBI/6.Semester/Berufspraktikum/Drug_Target_Network/data/id_le_na.bsv"

DRUGS_LIST = "./data/drugs_list.txt"
TARGETS_LIST = "./data/targets_list.txt"
GO_TERMS_LIST = "./data/go_terms_list.txt"
MATRIX_PACT = "./data/matrix_pact.npy"
MATRIX_DRUG_DISTANCE = "./data/matrix_drug_distance.npy"
MATRIX_TARGET_DISTANCE = "./data/matrix_target_distance.npy"
MATRIX_DRUG_ATC_DISTANCE = "./data/matrix_drug_atc_distance.npy"
MATRIX_TARGET_GO_DISTANCE = "./data/matrix_target_go_distance.npy"
MATRIX_GO_TERMS = "./data/matrix_go_terms.npy"
TARGET_CLASSES_GENERAL_GROUPS = "./data/targetClass.txt"
